### ISSUE TITLE
Ring.png

### ISSUE THREAD

**Issue by heschy** [DarceyLloyd/StargateSimulator#1]
Hello, in your repository is a file calles ring.png. I want to use this file in my Project. Is this a free to use File? Your reposirtory doesn't have a Licence file, so I do not know what i should do, please can you help me?

**Comment by DarceyLloyd** [comment]
It was a long time ago I created that now but it was a combination of images I found via google and then done some photoshop work on. So technically it's my work, feel free to use it anywhere / way you want.

**Comment by heschy** [comment]
Thank you.
